In [5]:
import numpy
import math

In [19]:
p = 7.0
r = numpy.array([11.2,4.7,6.6])
for i in r:
    x = numpy.sin(p/r)**3
    print(x[0:])

[ 0.20030151  0.99009101  0.66454238]
[ 0.20030151  0.99009101  0.66454238]
[ 0.20030151  0.99009101  0.66454238]


In [20]:
numpy.sin(p/r)**3

array([ 0.20030151,  0.99009101,  0.66454238])

In [21]:
for i in r:
    print(math.sin(p/i)**3)
    

0.20030150930292323
0.9900910096418035
0.6645423764180455


In [22]:
z = numpy.array([1,2,3])

numpy.sin(z/r)

array([ 0.08916713,  0.41280532,  0.43905397])